/*******************************************************************************
   Project : C script
   File    : code.h
   Date    : 2018.5.7-
   Note    : 実行環境の作業用スタック、中間コード領域
*******************************************************************************/
#ifndef EBCSCRIPT_CODE
#define EBCSCRIPT_CODE

/*                                                                   定数定義 */
/* -------------------------------------------------------------------------- */
/* 命令 */
typedef short ebcscript_instruction;

enum ebcscript_instruction_kind {
	/* 終了 */
	EBCSCRIPT_INSTRUCTION_EXIT,

	/* NOP */
	EBCSCRIPT_INSTRUCTION_NOP,

	/* フレーム確保・解放 */
	EBCSCRIPT_INSTRUCTION_PUSH_BP,
	EBCSCRIPT_INSTRUCTION_POP_BP,
	EBCSCRIPT_INSTRUCTION_ADD_SP,
	EBCSCRIPT_INSTRUCTION_SUB_SP,
	EBCSCRIPT_INSTRUCTION_MOV_SP_BP,
	EBCSCRIPT_INSTRUCTION_MOV_BP_SP,

	/* スタック操作 */
	EBCSCRIPT_INSTRUCTION_PUSH_IMM_C,
	EBCSCRIPT_INSTRUCTION_PUSH_IMM_S,
	EBCSCRIPT_INSTRUCTION_PUSH_IMM_I,
	EBCSCRIPT_INSTRUCTION_PUSH_IMM_L,
	EBCSCRIPT_INSTRUCTION_PUSH_IMM_F,
	EBCSCRIPT_INSTRUCTION_PUSH_IMM_D,
	EBCSCRIPT_INSTRUCTION_PUSH_IMM_P,
	EBCSCRIPT_INSTRUCTION_PUSH_IMM_OBJECT,

	EBCSCRIPT_INSTRUCTION_PUSH_GMEM_C,
	EBCSCRIPT_INSTRUCTION_PUSH_GMEM_S,
	EBCSCRIPT_INSTRUCTION_PUSH_GMEM_I,
	EBCSCRIPT_INSTRUCTION_PUSH_GMEM_L,
	EBCSCRIPT_INSTRUCTION_PUSH_GMEM_F,
	EBCSCRIPT_INSTRUCTION_PUSH_GMEM_D,
	EBCSCRIPT_INSTRUCTION_PUSH_GMEM_P,
	EBCSCRIPT_INSTRUCTION_PUSH_GMEM_OBJECT,

	EBCSCRIPT_INSTRUCTION_PUSH_LMEM_C,
	EBCSCRIPT_INSTRUCTION_PUSH_LMEM_S,
	EBCSCRIPT_INSTRUCTION_PUSH_LMEM_I,
	EBCSCRIPT_INSTRUCTION_PUSH_LMEM_L,
	EBCSCRIPT_INSTRUCTION_PUSH_LMEM_F,
	EBCSCRIPT_INSTRUCTION_PUSH_LMEM_D,
	EBCSCRIPT_INSTRUCTION_PUSH_LMEM_P,
	EBCSCRIPT_INSTRUCTION_PUSH_LMEM_OBJECT,

	EBCSCRIPT_INSTRUCTION_DUP_C,
	EBCSCRIPT_INSTRUCTION_DUP_S,
	EBCSCRIPT_INSTRUCTION_DUP_I,
	EBCSCRIPT_INSTRUCTION_DUP_L,
	EBCSCRIPT_INSTRUCTION_DUP_F,
	EBCSCRIPT_INSTRUCTION_DUP_D,
	EBCSCRIPT_INSTRUCTION_DUP_P,
	EBCSCRIPT_INSTRUCTION_DUP_OBJECT,

	EBCSCRIPT_INSTRUCTION_LOAD_C,
	EBCSCRIPT_INSTRUCTION_LOAD_S,
	EBCSCRIPT_INSTRUCTION_LOAD_I,
	EBCSCRIPT_INSTRUCTION_LOAD_L,
	EBCSCRIPT_INSTRUCTION_LOAD_F,
	EBCSCRIPT_INSTRUCTION_LOAD_D,
	EBCSCRIPT_INSTRUCTION_LOAD_P,
	EBCSCRIPT_INSTRUCTION_LOAD_OBJECT,

	EBCSCRIPT_INSTRUCTION_POP_GMEM_C,
	EBCSCRIPT_INSTRUCTION_POP_GMEM_S,
	EBCSCRIPT_INSTRUCTION_POP_GMEM_I,
	EBCSCRIPT_INSTRUCTION_POP_GMEM_L,
	EBCSCRIPT_INSTRUCTION_POP_GMEM_F,
	EBCSCRIPT_INSTRUCTION_POP_GMEM_D,
	EBCSCRIPT_INSTRUCTION_POP_GMEM_P,
	EBCSCRIPT_INSTRUCTION_POP_GMEM_OBJECT,

	EBCSCRIPT_INSTRUCTION_POP_LMEM_C,
	EBCSCRIPT_INSTRUCTION_POP_LMEM_S,
	EBCSCRIPT_INSTRUCTION_POP_LMEM_I,
	EBCSCRIPT_INSTRUCTION_POP_LMEM_L,
	EBCSCRIPT_INSTRUCTION_POP_LMEM_F,
	EBCSCRIPT_INSTRUCTION_POP_LMEM_D,
	EBCSCRIPT_INSTRUCTION_POP_LMEM_P,
	EBCSCRIPT_INSTRUCTION_POP_LMEM_OBJECT,

	EBCSCRIPT_INSTRUCTION_STORE_C,
	EBCSCRIPT_INSTRUCTION_STORE_S,
	EBCSCRIPT_INSTRUCTION_STORE_I,
	EBCSCRIPT_INSTRUCTION_STORE_L,
	EBCSCRIPT_INSTRUCTION_STORE_F,
	EBCSCRIPT_INSTRUCTION_STORE_D,
	EBCSCRIPT_INSTRUCTION_STORE_P,
	EBCSCRIPT_INSTRUCTION_STORE_OBJECT,

	/* 型キャスト */
	EBCSCRIPT_INSTRUCTION_C_TO_C,
	EBCSCRIPT_INSTRUCTION_C_TO_UC,
	EBCSCRIPT_INSTRUCTION_C_TO_S,
	EBCSCRIPT_INSTRUCTION_C_TO_US,
	EBCSCRIPT_INSTRUCTION_C_TO_I,
	EBCSCRIPT_INSTRUCTION_C_TO_UI,
	EBCSCRIPT_INSTRUCTION_C_TO_L,
	EBCSCRIPT_INSTRUCTION_C_TO_UL,
	EBCSCRIPT_INSTRUCTION_C_TO_F,
	EBCSCRIPT_INSTRUCTION_C_TO_D,
	EBCSCRIPT_INSTRUCTION_C_TO_P,

	EBCSCRIPT_INSTRUCTION_UC_TO_C,
	EBCSCRIPT_INSTRUCTION_UC_TO_UC,
	EBCSCRIPT_INSTRUCTION_UC_TO_S,
	EBCSCRIPT_INSTRUCTION_UC_TO_US,
	EBCSCRIPT_INSTRUCTION_UC_TO_I,
	EBCSCRIPT_INSTRUCTION_UC_TO_UI,
	EBCSCRIPT_INSTRUCTION_UC_TO_L,
	EBCSCRIPT_INSTRUCTION_UC_TO_UL,
	EBCSCRIPT_INSTRUCTION_UC_TO_F,
	EBCSCRIPT_INSTRUCTION_UC_TO_D,
	EBCSCRIPT_INSTRUCTION_UC_TO_P,

	EBCSCRIPT_INSTRUCTION_S_TO_C,
	EBCSCRIPT_INSTRUCTION_S_TO_UC,
	EBCSCRIPT_INSTRUCTION_S_TO_S,
	EBCSCRIPT_INSTRUCTION_S_TO_US,
	EBCSCRIPT_INSTRUCTION_S_TO_I,
	EBCSCRIPT_INSTRUCTION_S_TO_UI,
	EBCSCRIPT_INSTRUCTION_S_TO_L,
	EBCSCRIPT_INSTRUCTION_S_TO_UL,
	EBCSCRIPT_INSTRUCTION_S_TO_F,
	EBCSCRIPT_INSTRUCTION_S_TO_D,
	EBCSCRIPT_INSTRUCTION_S_TO_P,

	EBCSCRIPT_INSTRUCTION_US_TO_C,
	EBCSCRIPT_INSTRUCTION_US_TO_UC,
	EBCSCRIPT_INSTRUCTION_US_TO_S,
	EBCSCRIPT_INSTRUCTION_US_TO_US,
	EBCSCRIPT_INSTRUCTION_US_TO_I,
	EBCSCRIPT_INSTRUCTION_US_TO_UI,
	EBCSCRIPT_INSTRUCTION_US_TO_L,
	EBCSCRIPT_INSTRUCTION_US_TO_UL,
	EBCSCRIPT_INSTRUCTION_US_TO_F,
	EBCSCRIPT_INSTRUCTION_US_TO_D,
	EBCSCRIPT_INSTRUCTION_US_TO_P,

	EBCSCRIPT_INSTRUCTION_I_TO_C,
	EBCSCRIPT_INSTRUCTION_I_TO_UC,
	EBCSCRIPT_INSTRUCTION_I_TO_S,
	EBCSCRIPT_INSTRUCTION_I_TO_US,
	EBCSCRIPT_INSTRUCTION_I_TO_I,
	EBCSCRIPT_INSTRUCTION_I_TO_UI,
	EBCSCRIPT_INSTRUCTION_I_TO_L,
	EBCSCRIPT_INSTRUCTION_I_TO_UL,
	EBCSCRIPT_INSTRUCTION_I_TO_F,
	EBCSCRIPT_INSTRUCTION_I_TO_D,
	EBCSCRIPT_INSTRUCTION_I_TO_P,

	EBCSCRIPT_INSTRUCTION_UI_TO_C,
	EBCSCRIPT_INSTRUCTION_UI_TO_UC,
	EBCSCRIPT_INSTRUCTION_UI_TO_S,
	EBCSCRIPT_INSTRUCTION_UI_TO_US,
	EBCSCRIPT_INSTRUCTION_UI_TO_I,
	EBCSCRIPT_INSTRUCTION_UI_TO_UI,
	EBCSCRIPT_INSTRUCTION_UI_TO_L,
	EBCSCRIPT_INSTRUCTION_UI_TO_UL,
	EBCSCRIPT_INSTRUCTION_UI_TO_F,
	EBCSCRIPT_INSTRUCTION_UI_TO_D,
	EBCSCRIPT_INSTRUCTION_UI_TO_P,

	EBCSCRIPT_INSTRUCTION_L_TO_C,
	EBCSCRIPT_INSTRUCTION_L_TO_UC,
	EBCSCRIPT_INSTRUCTION_L_TO_S,
	EBCSCRIPT_INSTRUCTION_L_TO_US,
	EBCSCRIPT_INSTRUCTION_L_TO_I,
	EBCSCRIPT_INSTRUCTION_L_TO_UI,
	EBCSCRIPT_INSTRUCTION_L_TO_L,
	EBCSCRIPT_INSTRUCTION_L_TO_UL,
	EBCSCRIPT_INSTRUCTION_L_TO_F,
	EBCSCRIPT_INSTRUCTION_L_TO_D,
	EBCSCRIPT_INSTRUCTION_L_TO_P,

	EBCSCRIPT_INSTRUCTION_UL_TO_C,
	EBCSCRIPT_INSTRUCTION_UL_TO_UC,
	EBCSCRIPT_INSTRUCTION_UL_TO_S,
	EBCSCRIPT_INSTRUCTION_UL_TO_US,
	EBCSCRIPT_INSTRUCTION_UL_TO_I,
	EBCSCRIPT_INSTRUCTION_UL_TO_UI,
	EBCSCRIPT_INSTRUCTION_UL_TO_L,
	EBCSCRIPT_INSTRUCTION_UL_TO_UL,
	EBCSCRIPT_INSTRUCTION_UL_TO_F,
	EBCSCRIPT_INSTRUCTION_UL_TO_D,
	EBCSCRIPT_INSTRUCTION_UL_TO_P,

	EBCSCRIPT_INSTRUCTION_F_TO_C,
	EBCSCRIPT_INSTRUCTION_F_TO_UC,
	EBCSCRIPT_INSTRUCTION_F_TO_S,
	EBCSCRIPT_INSTRUCTION_F_TO_US,
	EBCSCRIPT_INSTRUCTION_F_TO_I,
	EBCSCRIPT_INSTRUCTION_F_TO_UI,
	EBCSCRIPT_INSTRUCTION_F_TO_L,
	EBCSCRIPT_INSTRUCTION_F_TO_UL,
	EBCSCRIPT_INSTRUCTION_F_TO_F,
	EBCSCRIPT_INSTRUCTION_F_TO_D,
	EBCSCRIPT_INSTRUCTION_F_TO_P,

	EBCSCRIPT_INSTRUCTION_D_TO_C,
	EBCSCRIPT_INSTRUCTION_D_TO_UC,
	EBCSCRIPT_INSTRUCTION_D_TO_S,
	EBCSCRIPT_INSTRUCTION_D_TO_US,
	EBCSCRIPT_INSTRUCTION_D_TO_I,
	EBCSCRIPT_INSTRUCTION_D_TO_UI,
	EBCSCRIPT_INSTRUCTION_D_TO_L,
	EBCSCRIPT_INSTRUCTION_D_TO_UL,
	EBCSCRIPT_INSTRUCTION_D_TO_F,
	EBCSCRIPT_INSTRUCTION_D_TO_D,
	EBCSCRIPT_INSTRUCTION_D_TO_P,

	EBCSCRIPT_INSTRUCTION_P_TO_C,
	EBCSCRIPT_INSTRUCTION_P_TO_UC,
	EBCSCRIPT_INSTRUCTION_P_TO_S,
	EBCSCRIPT_INSTRUCTION_P_TO_US,
	EBCSCRIPT_INSTRUCTION_P_TO_I,
	EBCSCRIPT_INSTRUCTION_P_TO_UI,
	EBCSCRIPT_INSTRUCTION_P_TO_L,
	EBCSCRIPT_INSTRUCTION_P_TO_UL,
	EBCSCRIPT_INSTRUCTION_P_TO_F,
	EBCSCRIPT_INSTRUCTION_P_TO_D,
	EBCSCRIPT_INSTRUCTION_P_TO_P,

	/* 算術演算 */
	EBCSCRIPT_INSTRUCTION_ADD_C,
	EBCSCRIPT_INSTRUCTION_ADD_UC,
	EBCSCRIPT_INSTRUCTION_ADD_S,
	EBCSCRIPT_INSTRUCTION_ADD_US,
	EBCSCRIPT_INSTRUCTION_ADD_I,
	EBCSCRIPT_INSTRUCTION_ADD_UI,
	EBCSCRIPT_INSTRUCTION_ADD_L,
	EBCSCRIPT_INSTRUCTION_ADD_UL,
	EBCSCRIPT_INSTRUCTION_ADD_F,
	EBCSCRIPT_INSTRUCTION_ADD_D,
	EBCSCRIPT_INSTRUCTION_ADD_P,

	EBCSCRIPT_INSTRUCTION_SUB_C,
	EBCSCRIPT_INSTRUCTION_SUB_UC,
	EBCSCRIPT_INSTRUCTION_SUB_S,
	EBCSCRIPT_INSTRUCTION_SUB_US,
	EBCSCRIPT_INSTRUCTION_SUB_I,
	EBCSCRIPT_INSTRUCTION_SUB_UI,
	EBCSCRIPT_INSTRUCTION_SUB_L,
	EBCSCRIPT_INSTRUCTION_SUB_UL,
	EBCSCRIPT_INSTRUCTION_SUB_F,
	EBCSCRIPT_INSTRUCTION_SUB_D,
	EBCSCRIPT_INSTRUCTION_SUB_P,

	EBCSCRIPT_INSTRUCTION_MUL_C,
	EBCSCRIPT_INSTRUCTION_MUL_UC,
	EBCSCRIPT_INSTRUCTION_MUL_S,
	EBCSCRIPT_INSTRUCTION_MUL_US,
	EBCSCRIPT_INSTRUCTION_MUL_I,
	EBCSCRIPT_INSTRUCTION_MUL_UI,
	EBCSCRIPT_INSTRUCTION_MUL_L,
	EBCSCRIPT_INSTRUCTION_MUL_UL,
	EBCSCRIPT_INSTRUCTION_MUL_F,
	EBCSCRIPT_INSTRUCTION_MUL_D,

	EBCSCRIPT_INSTRUCTION_DIV_C,
	EBCSCRIPT_INSTRUCTION_DIV_UC,
	EBCSCRIPT_INSTRUCTION_DIV_S,
	EBCSCRIPT_INSTRUCTION_DIV_US,
	EBCSCRIPT_INSTRUCTION_DIV_I,
	EBCSCRIPT_INSTRUCTION_DIV_UI,
	EBCSCRIPT_INSTRUCTION_DIV_L,
	EBCSCRIPT_INSTRUCTION_DIV_UL,
	EBCSCRIPT_INSTRUCTION_DIV_F,
	EBCSCRIPT_INSTRUCTION_DIV_D,

	EBCSCRIPT_INSTRUCTION_MOD_C,
	EBCSCRIPT_INSTRUCTION_MOD_UC,
	EBCSCRIPT_INSTRUCTION_MOD_S,
	EBCSCRIPT_INSTRUCTION_MOD_US,
	EBCSCRIPT_INSTRUCTION_MOD_I,
	EBCSCRIPT_INSTRUCTION_MOD_UI,
	EBCSCRIPT_INSTRUCTION_MOD_L,
	EBCSCRIPT_INSTRUCTION_MOD_UL,

	EBCSCRIPT_INSTRUCTION_INC_C,
	EBCSCRIPT_INSTRUCTION_INC_UC,
	EBCSCRIPT_INSTRUCTION_INC_S,
	EBCSCRIPT_INSTRUCTION_INC_US,
	EBCSCRIPT_INSTRUCTION_INC_I,
	EBCSCRIPT_INSTRUCTION_INC_UI,
	EBCSCRIPT_INSTRUCTION_INC_L,
	EBCSCRIPT_INSTRUCTION_INC_UL,
	EBCSCRIPT_INSTRUCTION_INC_F,
	EBCSCRIPT_INSTRUCTION_INC_D,
	EBCSCRIPT_INSTRUCTION_INC_P,

	EBCSCRIPT_INSTRUCTION_DEC_C,
	EBCSCRIPT_INSTRUCTION_DEC_UC,
	EBCSCRIPT_INSTRUCTION_DEC_S,
	EBCSCRIPT_INSTRUCTION_DEC_US,
	EBCSCRIPT_INSTRUCTION_DEC_I,
	EBCSCRIPT_INSTRUCTION_DEC_UI,
	EBCSCRIPT_INSTRUCTION_DEC_L,
	EBCSCRIPT_INSTRUCTION_DEC_UL,
	EBCSCRIPT_INSTRUCTION_DEC_F,
	EBCSCRIPT_INSTRUCTION_DEC_D,
	EBCSCRIPT_INSTRUCTION_DEC_P,

	EBCSCRIPT_INSTRUCTION_NEG_C,
	EBCSCRIPT_INSTRUCTION_NEG_UC,
	EBCSCRIPT_INSTRUCTION_NEG_S,
	EBCSCRIPT_INSTRUCTION_NEG_US,
	EBCSCRIPT_INSTRUCTION_NEG_I,
	EBCSCRIPT_INSTRUCTION_NEG_UI,
	EBCSCRIPT_INSTRUCTION_NEG_L,
	EBCSCRIPT_INSTRUCTION_NEG_UL,
	EBCSCRIPT_INSTRUCTION_NEG_F,
	EBCSCRIPT_INSTRUCTION_NEG_D,

	/* ビット演算 */
	EBCSCRIPT_INSTRUCTION_AND_C,
	EBCSCRIPT_INSTRUCTION_AND_S,
	EBCSCRIPT_INSTRUCTION_AND_I,
	EBCSCRIPT_INSTRUCTION_AND_L,

	EBCSCRIPT_INSTRUCTION_OR_C,
	EBCSCRIPT_INSTRUCTION_OR_S,
	EBCSCRIPT_INSTRUCTION_OR_I,
	EBCSCRIPT_INSTRUCTION_OR_L,

	EBCSCRIPT_INSTRUCTION_XOR_C,
	EBCSCRIPT_INSTRUCTION_XOR_S,
	EBCSCRIPT_INSTRUCTION_XOR_I,
	EBCSCRIPT_INSTRUCTION_XOR_L,

	EBCSCRIPT_INSTRUCTION_NOT_C,
	EBCSCRIPT_INSTRUCTION_NOT_S,
	EBCSCRIPT_INSTRUCTION_NOT_I,
	EBCSCRIPT_INSTRUCTION_NOT_L,

	EBCSCRIPT_INSTRUCTION_SHL_C,
	EBCSCRIPT_INSTRUCTION_SHL_S,
	EBCSCRIPT_INSTRUCTION_SHL_I,
	EBCSCRIPT_INSTRUCTION_SHL_L,

	EBCSCRIPT_INSTRUCTION_SHR_C,
	EBCSCRIPT_INSTRUCTION_SHR_S,
	EBCSCRIPT_INSTRUCTION_SHR_I,
	EBCSCRIPT_INSTRUCTION_SHR_L,

	/* 比較演算 */
	EBCSCRIPT_INSTRUCTION_LT_C,
	EBCSCRIPT_INSTRUCTION_LT_UC,
	EBCSCRIPT_INSTRUCTION_LT_S,
	EBCSCRIPT_INSTRUCTION_LT_US,
	EBCSCRIPT_INSTRUCTION_LT_I,
	EBCSCRIPT_INSTRUCTION_LT_UI,
	EBCSCRIPT_INSTRUCTION_LT_L,
	EBCSCRIPT_INSTRUCTION_LT_UL,
	EBCSCRIPT_INSTRUCTION_LT_F,
	EBCSCRIPT_INSTRUCTION_LT_D,
	EBCSCRIPT_INSTRUCTION_LT_P,

	EBCSCRIPT_INSTRUCTION_LE_C,
	EBCSCRIPT_INSTRUCTION_LE_UC,
	EBCSCRIPT_INSTRUCTION_LE_S,
	EBCSCRIPT_INSTRUCTION_LE_US,
	EBCSCRIPT_INSTRUCTION_LE_I,
	EBCSCRIPT_INSTRUCTION_LE_UI,
	EBCSCRIPT_INSTRUCTION_LE_L,
	EBCSCRIPT_INSTRUCTION_LE_UL,
	EBCSCRIPT_INSTRUCTION_LE_F,
	EBCSCRIPT_INSTRUCTION_LE_D,
	EBCSCRIPT_INSTRUCTION_LE_P,

	EBCSCRIPT_INSTRUCTION_GT_C,
	EBCSCRIPT_INSTRUCTION_GT_UC,
	EBCSCRIPT_INSTRUCTION_GT_S,
	EBCSCRIPT_INSTRUCTION_GT_US,
	EBCSCRIPT_INSTRUCTION_GT_I,
	EBCSCRIPT_INSTRUCTION_GT_UI,
	EBCSCRIPT_INSTRUCTION_GT_L,
	EBCSCRIPT_INSTRUCTION_GT_UL,
	EBCSCRIPT_INSTRUCTION_GT_F,
	EBCSCRIPT_INSTRUCTION_GT_D,
	EBCSCRIPT_INSTRUCTION_GT_P,

	EBCSCRIPT_INSTRUCTION_GE_C,
	EBCSCRIPT_INSTRUCTION_GE_UC,
	EBCSCRIPT_INSTRUCTION_GE_S,
	EBCSCRIPT_INSTRUCTION_GE_US,
	EBCSCRIPT_INSTRUCTION_GE_I,
	EBCSCRIPT_INSTRUCTION_GE_UI,
	EBCSCRIPT_INSTRUCTION_GE_L,
	EBCSCRIPT_INSTRUCTION_GE_UL,
	EBCSCRIPT_INSTRUCTION_GE_F,
	EBCSCRIPT_INSTRUCTION_GE_D,
	EBCSCRIPT_INSTRUCTION_GE_P,

	EBCSCRIPT_INSTRUCTION_EQ_C,
	EBCSCRIPT_INSTRUCTION_EQ_UC,
	EBCSCRIPT_INSTRUCTION_EQ_S,
	EBCSCRIPT_INSTRUCTION_EQ_US,
	EBCSCRIPT_INSTRUCTION_EQ_I,
	EBCSCRIPT_INSTRUCTION_EQ_UI,
	EBCSCRIPT_INSTRUCTION_EQ_L,
	EBCSCRIPT_INSTRUCTION_EQ_UL,
	EBCSCRIPT_INSTRUCTION_EQ_F,
	EBCSCRIPT_INSTRUCTION_EQ_D,
	EBCSCRIPT_INSTRUCTION_EQ_P,

	EBCSCRIPT_INSTRUCTION_NE_C,
	EBCSCRIPT_INSTRUCTION_NE_UC,
	EBCSCRIPT_INSTRUCTION_NE_S,
	EBCSCRIPT_INSTRUCTION_NE_US,
	EBCSCRIPT_INSTRUCTION_NE_I,
	EBCSCRIPT_INSTRUCTION_NE_UI,
	EBCSCRIPT_INSTRUCTION_NE_L,
	EBCSCRIPT_INSTRUCTION_NE_UL,
	EBCSCRIPT_INSTRUCTION_NE_F,
	EBCSCRIPT_INSTRUCTION_NE_D,
	EBCSCRIPT_INSTRUCTION_NE_P,

	/* 代入式 */
	EBCSCRIPT_INSTRUCTION_ASSGN_C,
	EBCSCRIPT_INSTRUCTION_ASSGN_UC,
	EBCSCRIPT_INSTRUCTION_ASSGN_S,
	EBCSCRIPT_INSTRUCTION_ASSGN_US,
	EBCSCRIPT_INSTRUCTION_ASSGN_I,
	EBCSCRIPT_INSTRUCTION_ASSGN_UI,
	EBCSCRIPT_INSTRUCTION_ASSGN_L,
	EBCSCRIPT_INSTRUCTION_ASSGN_UL,
	EBCSCRIPT_INSTRUCTION_ASSGN_F,
	EBCSCRIPT_INSTRUCTION_ASSGN_D,
	EBCSCRIPT_INSTRUCTION_ASSGN_P,
	EBCSCRIPT_INSTRUCTION_ASSGN_OBJECT,

	/* 局所ジャンプ */
	EBCSCRIPT_INSTRUCTION_JMP,

	EBCSCRIPT_INSTRUCTION_JMPT_C,
	EBCSCRIPT_INSTRUCTION_JMPT_UC,
	EBCSCRIPT_INSTRUCTION_JMPT_S,
	EBCSCRIPT_INSTRUCTION_JMPT_US,
	EBCSCRIPT_INSTRUCTION_JMPT_I,
	EBCSCRIPT_INSTRUCTION_JMPT_UI,
	EBCSCRIPT_INSTRUCTION_JMPT_L,
	EBCSCRIPT_INSTRUCTION_JMPT_UL,
	EBCSCRIPT_INSTRUCTION_JMPT_F,
	EBCSCRIPT_INSTRUCTION_JMPT_D,
	EBCSCRIPT_INSTRUCTION_JMPT_P,

	EBCSCRIPT_INSTRUCTION_JMPF_C,
	EBCSCRIPT_INSTRUCTION_JMPF_UC,
	EBCSCRIPT_INSTRUCTION_JMPF_S,
	EBCSCRIPT_INSTRUCTION_JMPF_US,
	EBCSCRIPT_INSTRUCTION_JMPF_I,
	EBCSCRIPT_INSTRUCTION_JMPF_UI,
	EBCSCRIPT_INSTRUCTION_JMPF_L,
	EBCSCRIPT_INSTRUCTION_JMPF_UL,
	EBCSCRIPT_INSTRUCTION_JMPF_F,
	EBCSCRIPT_INSTRUCTION_JMPF_D,
	EBCSCRIPT_INSTRUCTION_JMPF_P,

	/* 呼び出し・復帰 */
	EBCSCRIPT_INSTRUCTION_CALL_IMM,
	EBCSCRIPT_INSTRUCTION_CALL_PTR,
	EBCSCRIPT_INSTRUCTION_RET,
};

/*                                                                 構造体宣言 */
/* -------------------------------------------------------------------------- */
typedef struct ebcscript_stack ebcscript_stack;
struct ebcscript_stack {
	void *Head;
	size_t Size;
	void *Pointer;
};
/*
typedef struct ebcscript_code ebcscript_code;
struct ebcscript_code {
	void *Head;
	size_t Size;
	void *Pointer;
};
*/

/*                                                             グローバル変数 */
/* -------------------------------------------------------------------------- */
extern FILE *Ebcscript_Code_Fplog;
extern size_t Ebcscript_Code_MallocTotal;
extern void *(*Ebcscript_Code_malloc)(size_t Size);
extern void (*Ebcscript_Code_free)(void *);
extern void (*Ebcscript_Code_exit)(int);
extern void (*Ebcscript_Code_log)(const char *Fmt, ...);

/*                                                                   関数宣言 */
/* -------------------------------------------------------------------------- */
void Ebcscript_Code_onexit(void);

ebcscript_stack *Ebcscript_newStack(size_t Size);
void Ebcscript_deleteStack(ebcscript_stack *Stk);

void Ebcscript_Stack_pointLast(ebcscript_stack *Stk);

void Ebcscript_Stack_push_char(ebcscript_stack *Stk, char C);
void Ebcscript_Stack_push_short(ebcscript_stack *Stk, short S);
void Ebcscript_Stack_push_int(ebcscript_stack *Stk, int I);
void Ebcscript_Stack_push_long(ebcscript_stack *Stk, long L);
void Ebcscript_Stack_push_uchar(ebcscript_stack *Stk, unsigned char UC);
void Ebcscript_Stack_push_ushort(ebcscript_stack *Stk, unsigned short US);
void Ebcscript_Stack_push_uint(ebcscript_stack *Stk, unsigned int UI);
void Ebcscript_Stack_push_ulong(ebcscript_stack *Stk, unsigned long UL);
void Ebcscript_Stack_push_float(ebcscript_stack *Stk, float F);
void Ebcscript_Stack_push_double(ebcscript_stack *Stk, double D);
void Ebcscript_Stack_push_address(ebcscript_stack *Stk, void *P);
void Ebcscript_Stack_pop_char(ebcscript_stack *Stk, char *C);
void Ebcscript_Stack_pop_short(ebcscript_stack *Stk, short *S);
void Ebcscript_Stack_pop_int(ebcscript_stack *Stk, int *I);
void Ebcscript_Stack_pop_long(ebcscript_stack *Stk, long *L);
void Ebcscript_Stack_pop_uchar(ebcscript_stack *Stk, unsigned char *UC);
void Ebcscript_Stack_pop_ushort(ebcscript_stack *Stk, unsigned short *US);
void Ebcscript_Stack_pop_uint(ebcscript_stack *Stk, unsigned int *UI);
void Ebcscript_Stack_pop_ulong(ebcscript_stack *Stk, unsigned long *UL);
void Ebcscript_Stack_pop_float(ebcscript_stack *Stk, float *F);
void Ebcscript_Stack_pop_double(ebcscript_stack *Stk, double *D);
void Ebcscript_Stack_pop_address(ebcscript_stack *Stk, void **P);
void Ebcscript_Stack_add_sp(ebcscript_stack *Stk, int I);
void Ebcscript_Stack_sub_sp(ebcscript_stack *Stk, int I);

#endif
